title: garyhawes.co.uk
logo: /images/profile.png
mail: gary.hawes@googlemail.com
github: https://github.com/gaxze
linkedin: https://uk.linkedin.com/in/garyhawes
drupal: https://www.drupal.org/u/gaxze
bitbucket: https://www.bitbucket.org/gaxze
gitlab: https://www.gitlab.com/gaxze
stackoverflow: http://stackoverflow.com/users/293838/gaxze
twitter: https://www.twitter.com/gaxze
spotify: https://play.spotify.com/user/gaxze
links:
    guyhodge:
        name: Guy Hodge
        url: http://www.guyhodge.com/
        icon:
    joeroganpodcast:
        name: Joe Rogan Experience Podcast
        url: http://podcasts.joerogan.net/
        icon: fa-podcast

