title: garyhawes.co.uk
logo: /images/profile.png
mail: gary.hawes@googlemail.com
github: https://github.com/gaxze
linkedin: https://uk.linkedin.com/in/garyhawes
drupal: https://www.drupal.org/u/gaxze
bitbucket: https://www.bitbucket.org/gaxze
gitlab: https://www.gitlab.com/gaxze
stackoverflow: http://stackoverflow.com/users/293838/gaxze
twitter: https://www.twitter.com/gaxze
spotify: https://play.spotify.com/user/gaxze
links:
    guyhodge:
        name: Guy Hodge
        url: http://www.guyhodge.com/
        icon:
    joeroganpodcast:
        name: Joe Rogan Experience Podcast
        url: http://podcasts.joerogan.net/
        icon: fa-podcast
career:
    britishcouncil:
        org: British Council
        title: Drupal Software Engineer
        term: 2014-Present
        url: https://www.britishcouncil.org
        body: |
            <p>Some text</p>
    cityam:
        org: City AM
        title: Web Developer
        term: 2013-2014
        url: https://www.cityam.com
        body: |
            <p>Some text</p>
    ndp:
        org: New Digital Partnership
        title: Web Developer
        term: 2011-2013
        url: https://ndp-studio.com
        body: |
            <p>Some text</p>
    gradworks:
        org: Graduate Works
        title: Web Developer
        term: 2009-2011
        url: http://www.graduateworks.com/
        body: |
            <p>Some text</p>